version: '3.8'
services:

  database:
    image: postgres:latest
    container_name: database_container
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: always
    networks:
      - ft_transcendence

  server:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - POSTGRES_TYPE=${POSTGRES_TYPE}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - POSTGRES_DATABASE_PASSWORD=${POSTGRES_DATABASE_PASSWORD}
      - PORT=${PORT}
      - HOSTNAME=${HOSTNAME}
      - REACT_APP_HOSTNAME=${REACT_APP_HOSTNAME}
      - REACT_APP_PORT=${REACT_APP_PORT}
      - API_CALLBACK=${API_CALLBACK}
      - JWT_SECRET=${JWT_SECRET}
      - API_ID=${API_ID}
      - API_SECRET=${API_SECRET}
    depends_on:
      - database
    networks:
      - ft_transcendence
    ports:
      - "3000:3000"

networks:
  ft_transcendence:
